version: "2.1"

services:
  browser:
    build: ./browser
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: true
    privileged: true
