name: Browser code

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/browser.yml
      - browser/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/browser.yml
      - browser/**

defaults:
  run:
    working-directory: browser

jobs:
  test:
    name: Code quality, tests and code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Check code quality
        run: yarn lint
      - name: Check TypeScript code
        run: yarn build --noEmit
      - name: Run tests
        run: yarn test --coverage
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
          directory: browser
